package restwebservices;

public enum ResponseCodes {
    OK,
    CREATED,
    ACCEPTED,
    NO_CONTENT,
    MOVED_PERMANENTLY,
    FOUND,
    SEE_OTHER,
    NOT_MODIFIED,
    TEMPORARY_REDIRECT,
    BAD_REQUEST,
    UNAUTHORIZED,
    FORBIDDEN,
    NOT_FOUND,
    METHOD_NOT_ALLOWED,
    NOT_ACCEPTABLE,
    PRECONDITION_FAILED,
    UNSUPPORTED_MEDIA_TYPE,
    INTERNAL_SERVER_ERROR,
    NOT_IMPLEMENTED
}
